name: "Automated DORA Metrics"

description: "Effortlessly record DORA metrics for your software releases and seamlessly push them to Compass by Atlassian"

branding:
  color: purple
  icon: activity

inputs:
  command:
    description: "The command to run (calculate-metrics, notify-compass)"
    required: true
  COMPASS_USER_EMAIL:
    description: "COMPASS_USER_EMAIL environment variable"
  COMPASS_USER_API_KEY:
    description: "COMPASS_USER_API_KEY environment variable"
  COMPASS_METRICS_BASE_URL:
    description: "COMPASS_METRICS_BASE_URL environment variable"

runs:
  using: "docker"
  image: "docker://abhimishraa/dorametrics:latest"
